name: ThinkDSP companion

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup alr
      uses: alire-project/setup-alire@v2

    - name: Build
      run: >
        cd sinusoid ; alr build ; cd .. ;
        cd chirp ; alr build ; cd .. ;
        cd echirp ; alr build ; cd ..
                
    - name: Publish
      uses: actions/upload-artifact@v3
      with:
          name: "artifacts"
          path: |
            sinusoid/bin/sinusoid chirp/bin/chirp echirp/bin/echirp
