name: ThinkDSP companion

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Libraries
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libsndfile1 libsndfile1-dev libgsl-dev 
        version: 1.0

    - name: Setup alr
      uses: alire-project/setup-alire@v2

    - name: Build
      run: >
        pushd examples ; ./build.sh ; popd
      shell: bash

    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.1'
        token:  ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      run: |
        R -e "install.packages('rmarkdown')"

    - name: Build R Markdown
      run: |
        R -e "rmarkdown::render('examples/sinusoid/doc/sinusoid.Rmd')"

    - name: Publish
      uses: actions/upload-artifact@v3
      with:
          name: "artifacts"
          path: |
            ./examples/examples.zip
