name: ThinkDSP companion

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Libraries
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libsndfile1 libsndfile1-dev libgsl-dev texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
        version: 1.0


    - name: Setup alr
      uses: alire-project/setup-alire@v2
    
    - name: Setup pandoc
      uses: r-lib/actions/setup-pandoc@v2

    - name: Build
      run: >
        pushd examples ; ./build.sh ; popd
      shell: bash

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1'
        token:  ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      run: |
        R -e "install.packages(c('dplyr','ggplot2','plotly','tinytex','rmarkdown'))"

    - name: Build R Markdown
      run: |
        R -e "tinytex::install_tinytex(force=TRUE)"
        R -e "rmarkdown::render('examples/sinusoid/doc/sinusoid.Rmd')"
        R -e "rmarkdown::render('examples/chirp/doc/chirp.Rmd')"
        R -e "rmarkdown::render('examples/echirp/doc/echirp.Rmd')"
        R -e "rmarkdown::render('examples/triangle/doc/triangle.Rmd')"
        R -e "rmarkdown::render('examples/arith/doc/arith.Rmd')"
        R -e "rmarkdown::render('examples/freqd/doc/freqd.Rmd')"
        R -e "rmarkdown::render('examples/spect/doc/spect.Rmd')"
        cd examples ; zip docs.zip */*/*.pdf */*/*.html

    - name: Publish
      uses: actions/upload-artifact@v3
      with:
          name: "artifacts"
          path: |
            ./examples/examples.zip
            ./examples/docs.zip
